FROM python:2.7.11

ENV ELASTICKUBE_PATH    /opt/elastickube
ENV PYTHONPATH          /opt/elastickube

WORKDIR ${ELASTICKUBE_PATH}

ADD data   ${ELASTICKUBE_PATH}/data
ADD charts ${ELASTICKUBE_PATH}/charts

RUN pip install --no-compile tornado motor GitPython pyyaml

RUN curl -sL https://github.com/harbur/tide/releases/download/v0.3.0/tide_linux_amd64 > /usr/local/bin/tide && \
    chmod +x /usr/local/bin/tide

CMD ${ELASTICKUBE_PATH}/charts/entrypoint.sh
